development:
  dialect: postgres
  database: golium
  user: postgres
  password: this_is_a_secure_password
  host: postgresql
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@postgres:5432/golium_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@postgres:5432/golium_production?sslmode=disable"}}
